// hub/src/components/SpacesList.tsx
import { useState, useEffect } from "react";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

type Space = {
  id: string;
  name: string;
  subdomain: string;
  createdAt: string;
  status: string;
};

const BASE_DOMAIN = typeof window !== "undefined"
  ? window.location.hostname.split(".").slice(-2).join(".")
  : "example.com";

export function SpacesList() {
  const [spaces, setSpaces] = useState<Space[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    fetch("/api/spaces")
      .then((res) => res.json())
      .then((data) => {
        setSpaces(data.filter((s: Space) => s.status === "active"));
        setLoading(false);
      })
      .catch(() => {
        setError("Failed to load spaces");
        setLoading(false);
      });
  }, []);

  if (loading) {
    return <p className="text-muted-foreground">Loading spaces...</p>;
  }

  if (error) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-destructive">{error}</p>
        </CardContent>
      </Card>
    );
  }

  if (spaces.length === 0) {
    return (
      <Card>
        <CardContent className="py-12 text-center">
          <p className="mb-4 text-muted-foreground">No spaces yet</p>
          <Button asChild>
            <a href="/spaces/new">Create your first space</a>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {spaces.map((space) => (
        <Card key={space.id}>
          <CardHeader>
            <CardTitle>
              <a href={`/space?id=${space.id}`} className="hover:underline">
                {space.name}
              </a>
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm text-muted-foreground">
              {space.subdomain}.{BASE_DOMAIN}
            </p>
            <p className="mt-2 text-xs text-muted-foreground/60">
              Created: {new Date(space.createdAt).toLocaleDateString()}
            </p>
          </CardContent>
        </Card>
      ))}
    </div>
  );
}

// hub/src/components/SpacesList.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import * as Card from "$lib/components/ui/card";
  import { Button } from "$lib/components/ui/button";
  import CreateSpaceForm from "./CreateSpaceForm.svelte";
  import type { Space } from "$lib/types";

  let spaces: Space[] = $state([]);
  let loading = $state(true);
  let error = $state<string | null>(null);
  let hubHost = $state("");
  let createOpen = $state(false);

  onMount(async () => {
    hubHost = window.__hubHost;
    try {
      const data = await fetch("/api/spaces").then((r) => r.json());
      spaces = data.filter((s: Space) => s.status === "active");
    } catch {
      error = "Failed to load spaces";
    } finally {
      loading = false;
    }
  });

  function handleCreated(space: Space) {
    spaces = [...spaces, space];
  }
</script>

<CreateSpaceForm bind:open={createOpen} onCreated={handleCreated} />

<h2 class="text-2xl font-semibold mb-6">Spaces</h2>

{#if loading}
  <p class="text-muted-foreground">Loading spaces...</p>
{:else if error}
  <Card.Root>
    <Card.Content class="py-8 text-center">
      <p class="text-destructive">{error}</p>
    </Card.Content>
  </Card.Root>
{:else if spaces.length === 0}
  <Card.Root>
    <Card.Content class="py-12 text-center">
      <p class="mb-4 text-muted-foreground">No spaces yet</p>
      <Button onclick={() => (createOpen = true)}>Create your first space</Button>
    </Card.Content>
  </Card.Root>
{:else}
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    {#each spaces as space (space.id)}
      <Card.Root>
        <Card.Header>
          <Card.Title>
            <a href="http://{space.subdomain}.{hubHost}" class="hover:underline">
              {space.name}
            </a>
          </Card.Title>
        </Card.Header>
        <Card.Content>
          <p class="text-sm text-muted-foreground">
            {space.subdomain}.{hubHost}
          </p>
          <p class="mt-2 text-xs text-muted-foreground/60">
            Created: {new Date(space.createdAt).toLocaleDateString()}
          </p>
        </Card.Content>
      </Card.Root>
    {/each}
  </div>
{/if}
